### ISSUE TITLE
makeDendrogram needs to give options for what features cluster on

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterCells#23]
Need to be able to makeDendrogram on just the top x PCAs or the top x most variable genes rather than all features. Should probably also make two slots (cluster dendrogram and samples dendrogram), as well as not automatically making it with the clusterExperiment constructor.

**Comment by epurdom** [comment]
Moved the two slot issue to a different issue.

**Comment by drisso** [comment]
Fixed with fb6091d430b210cd4ef490767d108ccdb6259962
